[package]
name = "cpuid"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]

[dependencies]
kvm-bindings = { git = "https://github.com/aghecenco/kvm-bindings", branch = "serde_dev" }

kvm = { path = "../kvm" }
